### ISSUE TITLE
Long-polling not fully implemented?

### ISSUE THREAD

**Issue by itsdalmo** [buildkite/lifecycled#21]
It seems like the queue is created with long polling in mind:
https://github.com/buildkite/lifecycled/blob/master/queue.go#L56

But the API call seems to be hardcoded to not utilise it?:
https://github.com/buildkite/lifecycled/blob/master/queue.go#L104

Might be wrong, but according to the AWS SDK Go documentation it seems like `WaitTimeSeconds` has to be set to > 0 seconds as well if you want to do long polling.

**Comment by lox** [comment]
Yup, I think you are right. It was brought in via https://github.com/buildkite/lifecycled/pull/11, but doesn't look like `WaitTimeSeconds` got set correctly. 

Thoughts on whether we need `WaitTimeSeconds` to be configurable or just a fixed value?

**Comment by itsdalmo** [comment]
> Thoughts on whether we need WaitTimeSeconds to be configurable or just a fixed value?

Think a fixed value should be fine since we can use `context.Context` to exit early.
