### ISSUE TITLE
Update vendored dependencies (some are >2 years old)

### ISSUE THREAD

**Issue by itsdalmo** [buildkite/lifecycled#27]
Might be time to upgrade them, e.g. `logrus` supports some new patterns so we can pass a logger between functions and eventually (hopefully) write tests.

What are you using for managing dependencies? Would you consider swapping to `dep`?

**Comment by lox** [comment]
I reckon we might stay with `govendor` as we use it across all our projects. The plan is to swap to go modules once 1.11 has had some time to settle in. I'll drop a PR with an update to vendors.

**Comment by lox** [comment]
Closing in favor of https://github.com/buildkite/lifecycled/pull/29
