### ISSUE TITLE
This app solve this type of problem?

### ISSUE THREAD

**Issue by Urahara** [buildkite/lifecycled#65]
Sorry for bad title.

My autoscalling is configured to start/terminate instance based on # of avaliables messages in queue, but sometimes when i processing something in machines and my # of messages less than my config, my autoscaling trigger to terminate instances, so i end losting message in the middle of processing (even though I'm running like a service via systemd).

When i shutdown/reboot that instance wait for my service, but when i "terminate" its like its ignore (i received signal but my instance is killed before the completation of task).

**Comment by lox** [comment]
Yup, lifecycled can be used to delay autoscaling killing your hosts until they have finished work!.
