### ISSUE TITLE
Outdated flag in Terraform example

### ISSUE THREAD

**Issue by qrilka** [buildkite/lifecycled#78]
In https://github.com/buildkite/lifecycled/blob/master/terraform/modules/example/cloud-config.yml#L19 I see `--spot` flag being used but it doesn't appear to exist anymore:
```
$ lifecycled --spot
lifecycled: error: unknown long flag '--spot', try --help
```
I suppose `--no-spot` (or actually not setting it) replaced `--spot`?

**Comment by itsdalmo** [comment]
This has been fixed in #81 , thanks for reporting 🙌
