### ISSUE TITLE
Outdated AWS SDK

### ISSUE THREAD

**Issue by asiragusa** [buildkite/lifecycled#86]
The current AWS SDK (v1.15.68) does not support IMDS v2 https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

A `go get -u github.com/aws/aws-sdk-go` will fixes the issue, I have tested with a local build.

**Comment by lox** [comment]
Closed via #88
